import React, { Component } from "react";
import { Text, View, Button } from "react-native";
import { TextInput } from "react-native-gesture-handler";
import AsyncStorage from '@react-native-async-storage/async-storage';
import { styles } from "./Styles/ReceberCodigoConfirmarStyles";


export default class ReceberCodigoConfirmar extends Component {
    constructor({ route, navigation }){
        super();
        const { value, publicName, publicPhoto } = route.params;
        this.state = {
            navigation: navigation,
            value: value,
            publicName: '',
            publicPhoto: '',
        }
        console.log(this.state)

    }

    //storing information this phone """""" NOT USED IN THIS PAGE """" TESTER
    storeData = async (value) => {
        try {
        const jsonValue = JSON.stringify(value)
        await AsyncStorage.setItem('@phoneSaveTeste4', jsonValue)
        } catch (e) {
        // saving error
        }
    }

    validateSecretCode(){
        let code = '1234'//code generated by server end send to user validade
        let userCode = '1234'
        if(userCode == code){
            try{
                this.storeData(this.state)
                this.state.navigation.navigate('LogadoApp', {
                    value: this.state.value,
                    publicName: this.state.publicName,
                    publicPhoto: this.state.publicPhoto,

                })
            }catch{
                this.storeData(this.state)
                this.state.navigation.navigate('LogadoApp', {
                    value: this.state.value,
                    publicName: this.state.publicName,
                    publicPhoto: this.state.publicPhoto,

                })
                

            }
            
        }
        
    }

    render(){
        //this.validateSecretCode()//
       
        return (
            <View style={styles.container}>
                <Text>Validando o número: {this.state.value}</Text>
                <Text>Insira o código que recebeu por SMS</Text>
                <TextInput
                    style={styles.inputStyle}
                    autoFocus={true}
                    keyboardType="numeric"
                    placeholder="---"
 
                >
                    
                </TextInput>

                <View style={styles.viewDoBtn}>
                    <Button 
                        title='Continuar'
                        onPress=
                        {
                            () => this.state.navigation.navigate('ReceberFoto', {
                                value: this.state.value
                            })
                        }
                    >
                    </Button>
                </View>
                
            </View>
        )
    }

}

